export const LOANS_SERVICE_API = process.env.NEXT_PUBLIC_LOANS_SERVICE_API_ENV ?? ''
export const LOANS_SERVICE_KEY = process.env.NEXT_PUBLIC_LOANS_SERVICE_KEY_ENV ?? ''
export const TERMS_AND_CONDITIONS_URL = process.env.NEXT_PUBLIC_TERMS_AND_CONDITIONS_URL_ENV ?? ''
